- name: configure cart server
  hosts: cart
  become: yes

  tasks:
   
   - name: enable module 20 in nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: present

   - name: create system user
     ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      comment: roboshop system user

   - name: delete app directory  # useful when new app version releases
     ansible.builtin.file: 
      path: /app
      state: directory

   - name: create app directory
     ansible.builtin.file:
      path: /app
      state: directory

   - name: download application code from external source  
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip
      
   - name: unzip/extract the downloaded code
     ansible.builtin.archive:
      path: /tmp/cart.zip 
      dest: /app
     args:
      chdir: /app   

   - name: install the dependencies
     community.general.npm:
      path: /app
     args:
      chdir: /app 

   - name: setup the service in systemd
     ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service

   - name: daemon reload
     ansible.builtin.systemd_service:
      daemon_reload: true 

   - name: start the service
     ansible.builtin.service:
      name: cart
      enabled: yes
      state: restarted     
        