- name: configure my sql server
  hosts: mysql
  become: yes

  tasks:
   - name: install my sql
     ansible.builtin.dnf:
      name: mysql-server
      state: present

   - name: start and enable service
     ansible.builtin.service:
      name: mysqld 
      state: restarted
      enabled: yes

   - name: change root password
     ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

   - name: Verify MySQL is reachable 
     ansible.builtin.wait_for:
      host: mysql-dev.learnawsdevops.online
      port: 3306
      timeout: 10 
     

 # To check health status of mysqld from other servers (control node)
 # telnet mysql-dev.learnawsdevops.online 3306      