- name: create EC2 instance
  hosts: local
  connection: local

  vars:
   ami_id: ami-0220d79f3f480ecf5
   sg_id: sg-00389248674030ff8

  tasks:
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
     name: "Roboshop"
     securtity_group: "{{sg-id}}"
     instance_type: "t3.micro"
     image_id: "{{ami-id}}"
     tags:
      Project: "Roboshop"
      Environment: "Dev"
      
